### ISSUE TITLE
Add ImgBot on Branding and hackathons repository

### ISSUE THREAD

**Issue by kcoder63** [EddieHubCommunity/Branding#10]
Run an [ImgBot ](https://github.com/marketplace/imgbot/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4xNzQ5) on [Branding](https://github.com/EddieHubCommunity/Branding)  and [Hackathons](https://github.com/EddieHubCommunity/Hackathons) repositories to deal with files

**Comment by eddiejaoude** [comment]
Great idea 👍

**Comment by kcoder63** [comment]
The bot needs to be installed by the owner or anyone who has access so I think others won't be able to work on this issue

**Comment by eddiejaoude** [comment]
oh you are right 👍

**Comment by eddiejaoude** [comment]
Here is the PR, how does it look? https://github.com/EddieHubCommunity/Branding/pull/12

**Comment by kcoder63** [comment]
Looks good to me!

**Comment by eddiejaoude** [comment]
Great, thank you! Merged :)
