### ISSUE TITLE
Suggest adding an Image as Logo

### ISSUE THREAD

**Issue by WebShivam** [EddieHubCommunity/Branding#13]
![eddie-logo-png](https://user-images.githubusercontent.com/64413107/114101099-e069e800-98e2-11eb-8788-48fcdae22712.png)

I designed this logo and I'd like to request you to use this as your logo if possible. If you didn't like this please put this in "Assets" category as my contribution

**Comment by eddiejaoude** [comment]
Thank you foe this 👍 . We have a `community` folder, you can add it there if you like
