### ISSUE TITLE
Feat: Vyvy-vi's art

### ISSUE THREAD

**Issue by Vyvy-vi** [EddieHubCommunity/Branding#15]
### Description:
Addition of all art from me(@Vyvy-vi)

### Questions:
- Should I upload actual pictures in the repo?
OR
- Can I embed them in a markdown file?

**Comment by vinzvinci** [comment]
I think it's better to upload the **actual art in the repo**. coz you might have a lot of art might come soon. Then only one (1) markdown file per **creator**.

**Comment by Vyvy-vi** [comment]
I'm afraid of adding too many binary files in a github repo

**Comment by starlightknown** [comment]
I think embedding them in markdown would be better so that every art could be seen there at one place and one glance.

**Comment by Vyvy-vi** [comment]
:(
