### ISSUE TITLE
Feat: New banner art

### ISSUE THREAD

**Issue by starlightknown** [EddieHubCommunity/Branding#17]
I made a banner similar to Siddharth's as you mentioned once. I'll put it here for now since I don't know where to add it.
Picture here(I made a GIF version too)
if you want to make or suggest some edits, hope you like it :)
![Eddie jaoude](https://user-images.githubusercontent.com/74637789/116118747-432cf300-a6db-11eb-8e5a-692aaf1c7d94.png)

**Comment by eddiejaoude** [comment]
OMG 😱 ❤️ this is AMAZING 💥

**Comment by eddiejaoude** [comment]
I think it should go in the repo under the `community` section

**Comment by kaiwalyakoparkar** [comment]
Ok I will add the image and gif both there

**Comment by starlightknown** [comment]
Alright, should I make a PR for this ?

**Comment by starlightknown** [comment]
> OMG 😱 ❤️ this is AMAZING 💥

Glad you liked it 😄

**Comment by kaiwalyakoparkar** [comment]
If you want go ahead. But add image and gif both

**Comment by kaiwalyakoparkar** [comment]
> > OMG scream heart this is AMAZING boom
> 
> Glad you liked it

Haha Hope eddie uses it in the intro of the new course which is comming next

**Comment by starlightknown** [comment]
> If you want go ahead. But add image and gif both

Yep will do!

**Comment by eddiejaoude** [comment]
> Haha Hope eddie uses it in the intro of the new course which is comming next

lol I will find somewhere to use it for sure!!

**Comment by eddiejaoude** [comment]
Is it possible to have a version with the text? it would be more flexible for me to use in different situations 🤓

**Comment by starlightknown** [comment]
> Is it possible to have a version with the text? it would be more flexible for me to use in different situations nerd_face

yeah sure, you mean without text?

**Comment by kaiwalyakoparkar** [comment]
Ok! I will create one and send it to @starlightknown and then she can add it to PR.

**Comment by starlightknown** [comment]
> Ok! I will create one and send it to @starlightknown and then she can add it to PR.

done it already. Plus I removed the link

**Comment by eddiejaoude** [comment]
Yes sorry, "without" the text 👍

**Comment by vinzvinci** [comment]
I suggest make it big letter H. **GitHub** not ~~Github~~

**Comment by starlightknown** [comment]
> I suggest make it big letter H. **GitHub** not ~Github~

Maybe in the next one and I made a no text version so it's good for edits.

**Comment by siddharthdayalwal** [comment]
Also, try adding 2 more images at the top which will make it a perfect pyramid, and align the images accordingly! :nerd_face:

**Comment by starlightknown** [comment]
Will do jt. Thank you for suggesting :)
