### ISSUE TITLE
Hubber No 13 & 15 Is same 😕 

### ISSUE THREAD

**Issue by rohank2502** [EddieHubCommunity/Branding#23]
Are they both really the same or just I am getting Confused !! 

![Screenshot 2021-05-11 205938](https://user-images.githubusercontent.com/76584243/117842930-0268d880-b29c-11eb-8deb-26a0cd82d554.png)

**Comment by WebShivam** [comment]
First of all I'd appreciate you for raising the issue and trying to clear this confusion
Yes, they both looks similar but when I closely looked them I found the first Hubber is wearing Hoodie and the other one is wearing Tees, so there's a difference between them and they're not same 🙂 
I hope it clears your doubt 🙂
