### ISSUE TITLE
Add a branding page on the website

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/Branding#27]
It'd be great if you could add a specific page for the branding. For example, Discord has its own [branding](https://discord.com/branding) page, and it also includes what you can do with the logos and what you can't do. I can also help with writing some guidelines in case you want.

Thanks. 🙂

**Comment by Panquesito7** [comment]
Can someone remove that label, please? Thanks.

**Comment by Kartik2220** [comment]
@Panquesito7  hey can you explain me in some detailed i would like to work on this issue:)

**Comment by AliMora83** [comment]
Is it still Open? 🤔

**Comment by eddiejaoude** [comment]
I will assign to @SaraJaoude

**Comment by SaraJaoude** [comment]
We already have a page for branding (including branding guidelines) on the EddieHub Website: https://www.eddiehub.org/branding

I will update the Branding README to include a link to that page.
