### ISSUE TITLE
A colour seems missing

### ISSUE THREAD

**Issue by adityaraute** [EddieHubCommunity/Branding#28]
The Readme doesn't mention the Hex code for this lightest green colour that forms the other half of that arc on the circle in Hubber's tablet.

![image](https://user-images.githubusercontent.com/43912470/126686179-b4e6a258-350f-4055-8968-d511f04f25f8.png)

**Comment by divyakumari12** [comment]
I don't think so

**Comment by adityaraute** [comment]
Why? It isn't mentioned anywhere right?

**Comment by ShlokMohanty** [comment]
i think the hex code for this light green colour should be #a5f0b9? @adityaraute

**Comment by adityaraute** [comment]
An online tool I checked with shows the hex code as #94c789

**Comment by ShlokMohanty** [comment]
ohh ok so now what needs to be done @adityaraute  for this issue .

**Comment by adityaraute** [comment]
The colour needs to be added in this list: 
![image](https://user-images.githubusercontent.com/43912470/133816912-5ad596a3-1df0-447c-9ec1-61ece05ea353.png)

**Comment by ShlokMohanty** [comment]
@adityaraute can you provide the link for the same ?
the colours list that is above if you could provide its url ?

**Comment by adityaraute** [comment]
It's the README file of this very Repository.

**Comment by eddiejaoude** [comment]
Thank you for your feedback! I think the lighter green colour is an opacity rather than a different colour. I will close this issue for now
