### ISSUE TITLE
[FEAT]: Hubber Public Speaking Pose

### ISSUE THREAD

**Issue by ghost** [EddieHubCommunity/Branding#31]
Hubber is somewhat similar to this position:
![image](https://user-images.githubusercontent.com/76587897/128593071-d6c2c858-df53-415d-90d1-677e6cfd5f4b.png)

**Comment by gouravmohanty7070** [comment]
Can I know more about the issue so that I could contribute?

**Comment by krishdevdb** [comment]
Design a pose for our mascot hubber where is the hubber is holding a microphone

**Comment by gouravmohanty7070** [comment]
Oh. So it's kind of a designing task?

**Comment by krishdevdb** [comment]
> Oh. So it's kind of a designing task?

yep graphic design kind of

**Comment by adityaraute** [comment]
Wondering if anyone can contribute here

**Comment by AliMora83** [comment]
I would love to work on this issue 🥳

**Comment by eddiejaoude** [comment]
Thank you for the suggestion. I will close this issue for now as we are not getting new poses at the moment
