### ISSUE TITLE
EDDIE-HUB Brand Name not visible in Dark Mode

### ISSUE THREAD

**Issue by itsarghyadas** [EddieHubCommunity/Branding#33]
In README.md file I saw your org name "EDDIE HUB" at the bottom of the Page.
(HUB) is not visible in "Dark Mode"
Adding a screenshot...

![image](https://user-images.githubusercontent.com/89768406/134362775-e2c39761-9800-4767-80e7-4d22d57e0c03.png)

**Comment by adityaraute** [comment]
Good of you to highlight this. Important issue

**Comment by minami2k** [comment]
you can add a label to this issue

**Comment by marpit19** [comment]
you can add a label to this issue

**Comment by avneesh0612** [comment]
Hey, can I take up this?
