### ISSUE TITLE
Discussion: Thumbnail Contest

### ISSUE THREAD

**Issue by adityaraute** [EddieHubCommunity/Branding#4]
Since we have a #ux-ui channel in our Discord, how about a thumbnail contest? Let us all design some thumbnails for your next stream, best one gets shoutout and you use that thumbnail.

**Comment by eddiejaoude** [comment]
Ideas from Discord discussion...

Rules
- file resolution `1280x720`
- must have a photo of Eddie in it (multiple options will be supplied)
- voluntary only
- no promise that these will be used

Guidelines
- any stock photos used must be royalty free and include links to their source

Prizes
- GitHub stickers for 1st, 2nd, 3rd

Questions
- community votes for winners

**Comment by adityaraute** [comment]
I think the winning thumbnail should definitely be used, else people will make memes instead of appropriate thumbnails.

Extension of the required file?

**Comment by eddiejaoude** [comment]
> I think the winning thumbnail should definitely be used, else people will make memes instead of appropriate thumbnails.

fair point 👍 

> Extension of the required file?

I will update my message, I think it should be `jpg`

**Comment by adityaraute** [comment]
Then let's fix a date and go to town with this.

**Comment by eddiejaoude** [comment]
lol soon 👍 . I am keen to continue working on EddieCon too, I wonder if we do it as part of that too 🤔 (@nhcarrigan what do you think)

**Comment by adityaraute** [comment]
What's this now?
Do we all dress up as you?

**Comment by nhcarrigan** [comment]
> lol soon 👍 . I am keen to continue working on EddieCon too, I wonder if we do it as part of that too 🤔 (@nhcarrigan what do you think)

This could be an excellent idea - though we'll have to ensure we integrate it in a way that folks don't need to attend a voice call to participate in the contest. 🙂

**Comment by eddiejaoude** [comment]
> Do we all dress up as you?

LOL oh no @adityaraute , I hope not 😱 . It will be the community sharing their knowledge in short talks, and more

**Comment by eddiejaoude** [comment]
> This could be an excellent idea - though we'll have to ensure we integrate it in a way that folks don't need to attend a voice call to participate in the contest. 🙂

@nhcarrigan yes true 👍
