### ISSUE TITLE
Typo in color name

### ISSUE THREAD

**Issue by Evavic44** [EddieHubCommunity/Branding#42]
<img src="https://user-images.githubusercontent.com/62628408/145672202-c889df94-870c-4fad-b45e-914e0f6b0985.png" width="500px">

I believe the word ``Nex`` was intended to be ``Hex``

**Comment by krishguptadev** [comment]
Wow 👀 So many typos and no one noticed 😆

**Comment by Evavic44** [comment]
Lol, 😂 hey @krishguptadev what will be required to fix this?

**Comment by krishguptadev** [comment]
> Lol, 😂 hey @krishguptadev what will be required to fix this?

IDK, maybe the one who added this image has an editable copy of this...

**Comment by Pradumnasaraf** [comment]
Oops, that's a huge error.
@Evavic44  are you working on this? or I should fix this?

**Comment by Evavic44** [comment]
Sure, go ahead @Pradumnasaraf
