### ISSUE TITLE
[DOCS] Some images in the README file in the Branding repo keeps repeating

### ISSUE THREAD

**Issue by rahul-nl** [EddieHubCommunity/Branding#57]
### Description

**Some images in the README file in the Branding repo keeps repeating.**
Removing these repeating images would make the file clean and easy to scroll.

### Screenshots

![image](https://user-images.githubusercontent.com/45726796/190887782-f41e4810-40ea-4846-858c-91b8b66ef91c.png)

**Comment by eddiejaoude** [comment]
Thank you but these images are different, 1 is wearing a shirt and the other is wearing a hoodie.
