### ISSUE TITLE
[DOCS] Some images in the README file in the Branding repo keeps repeating

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [EddieHubCommunity/Branding#60]
### Description

Some images in the README file in the Branding repo keeps repeating
- The first and third image in screenshot

### Screenshots

![image](https://user-images.githubusercontent.com/87495134/219348995-c7a9a494-5ac7-4b6c-b526-d38bc4570e45.png)

**Comment by GitWiz01** [comment]
@Soumya-Kushwaha I would like to work on this issue ma'am
