### ISSUE TITLE
Discussion: Attribution table

### ISSUE THREAD

**Issue by Vyvy-vi** [EddieHubCommunity/Branding#9]
We could make a markdown table for who added what art, with links to that art in a CONTRIBUTORS/ATTRIBUTION.md file.
This would help in doing the following:
- Indexing all the art
- Help in identifying creators of the art (esp. when multiple people worked on the same piece)

**Comment by eddiejaoude** [comment]
Nice 👍  sounds great 🤓

**Comment by rohank2502** [comment]
Will like to do it !!

**Comment by eddiejaoude** [comment]
Great 👍
